# Check out: https://github.com/GlowCheese/deepmosa
import pytest
import isort.files as module_0
import isort.settings as module_1
import isort.wrap_modes as module_2

def test_case_0():
    var_0 = None
    var_1 = module_0.find(var_0, var_0, var_0, var_0)

def test_case_1():
    var_0 = []
    var_1 = 'fle2.py'
    var_2 = module_0.find(var_1, var_0, var_0, var_0)
    with pytest.raises(AttributeError):
        var_3 = list(var_2)

def test_case_2():
    var_0 = []
    var_1 = module_1.Config()
    assert f'{type(var_1).__module__}.{type(var_1).__qualname__}' == 'isort.settings.Config'
    assert var_1.py_version == 'py3'
    assert f'{type(var_1.force_to_top).__module__}.{type(var_1.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.force_to_top) == 0
    assert f'{type(var_1.skip).__module__}.{type(var_1.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.skip) == 19
    assert f'{type(var_1.extend_skip).__module__}.{type(var_1.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.extend_skip) == 0
    assert f'{type(var_1.skip_glob).__module__}.{type(var_1.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.skip_glob) == 0
    assert f'{type(var_1.extend_skip_glob).__module__}.{type(var_1.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.extend_skip_glob) == 0
    assert var_1.skip_gitignore is False
    assert var_1.line_length == 79
    assert var_1.wrap_length == 0
    assert var_1.line_ending == ''
    assert var_1.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_1.no_sections is False
    assert f'{type(var_1.known_future_library).__module__}.{type(var_1.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.known_future_library) == 1
    assert f'{type(var_1.known_third_party).__module__}.{type(var_1.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.known_third_party) == 0
    assert f'{type(var_1.known_first_party).__module__}.{type(var_1.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.known_first_party) == 0
    assert f'{type(var_1.known_local_folder).__module__}.{type(var_1.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.known_local_folder) == 0
    assert f'{type(var_1.known_standard_library).__module__}.{type(var_1.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.known_standard_library) == 234
    assert f'{type(var_1.extra_standard_library).__module__}.{type(var_1.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.extra_standard_library) == 0
    assert var_1.known_other == {}
    assert var_1.multi_line_output == module_2.WrapModes.GRID
    assert var_1.forced_separate == ()
    assert var_1.indent == '    '
    assert var_1.comment_prefix == '  #'
    assert var_1.length_sort is False
    assert var_1.length_sort_straight is False
    assert f'{type(var_1.length_sort_sections).__module__}.{type(var_1.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.length_sort_sections) == 0
    assert f'{type(var_1.add_imports).__module__}.{type(var_1.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.add_imports) == 0
    assert f'{type(var_1.remove_imports).__module__}.{type(var_1.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.remove_imports) == 0
    assert var_1.append_only is False
    assert var_1.reverse_relative is False
    assert var_1.force_single_line is False
    assert var_1.single_line_exclusions == ()
    assert var_1.default_section == 'THIRDPARTY'
    assert var_1.import_headings == {}
    assert var_1.import_footers == {}
    assert var_1.balanced_wrapping is False
    assert var_1.use_parentheses is False
    assert var_1.order_by_type is True
    assert var_1.atomic is False
    assert var_1.lines_before_imports == -1
    assert var_1.lines_after_imports == -1
    assert var_1.lines_between_sections == 1
    assert var_1.lines_between_types == 0
    assert var_1.combine_as_imports is False
    assert var_1.combine_star is False
    assert var_1.include_trailing_comma is False
    assert var_1.from_first is False
    assert var_1.verbose is False
    assert var_1.quiet is False
    assert var_1.force_adds is False
    assert var_1.force_alphabetical_sort_within_sections is False
    assert var_1.force_alphabetical_sort is False
    assert var_1.force_grid_wrap == 0
    assert var_1.force_sort_within_sections is False
    assert var_1.lexicographical is False
    assert var_1.group_by_package is False
    assert var_1.ignore_whitespace is False
    assert f'{type(var_1.no_lines_before).__module__}.{type(var_1.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.no_lines_before) == 0
    assert var_1.no_inline_sort is False
    assert var_1.ignore_comments is False
    assert var_1.case_sensitive is False
    assert f'{type(var_1.sources).__module__}.{type(var_1.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_1.sources) == 1
    assert var_1.virtual_env == ''
    assert var_1.conda_env == ''
    assert var_1.ensure_newline_before_comments is False
    assert var_1.directory == '/workspace'
    assert var_1.profile == ''
    assert var_1.honor_noqa is False
    assert f'{type(var_1.src_paths).__module__}.{type(var_1.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_1.src_paths) == 2
    assert var_1.remove_redundant_aliases is False
    assert var_1.float_to_top is False
    assert var_1.filter_files is False
    assert var_1.formatter == ''
    assert var_1.formatting_function is None
    assert var_1.color_output is False
    assert f'{type(var_1.treat_comments_as_code).__module__}.{type(var_1.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.treat_comments_as_code) == 0
    assert var_1.treat_all_comments_as_code is False
    assert f'{type(var_1.supported_extensions).__module__}.{type(var_1.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.supported_extensions) == 4
    assert f'{type(var_1.blocked_extensions).__module__}.{type(var_1.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.blocked_extensions) == 1
    assert f'{type(var_1.constants).__module__}.{type(var_1.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.constants) == 0
    assert f'{type(var_1.classes).__module__}.{type(var_1.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.classes) == 0
    assert f'{type(var_1.variables).__module__}.{type(var_1.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.variables) == 0
    assert var_1.dedup_headings is False
    assert var_1.only_sections is False
    assert var_1.only_modified is False
    assert var_1.combine_straight_imports is False
    assert var_1.auto_identify_namespace_packages is True
    assert f'{type(var_1.namespace_packages).__module__}.{type(var_1.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_1.namespace_packages) == 0
    assert var_1.follow_links is True
    assert var_1.indented_import_headings is True
    assert var_1.honor_case_in_force_sorted_sections is False
    assert var_1.sort_relative_in_force_sorted_sections is False
    assert var_1.overwrite_in_place is False
    assert var_1.reverse_sort is False
    assert var_1.star_first is False
    assert var_1.git_ls_files == {}
    assert var_1.format_error == '{error}: {message}'
    assert var_1.format_success == '{success}: {message}'
    assert var_1.sort_order == 'natural'
    assert var_1.sort_reexports is False
    assert var_1.split_on_trailing_comma is False
    assert module_1.TYPE_CHECKING is False
    assert module_1.profiles == {'black': {'multi_line_output': 3, 'include_trailing_comma': True, 'split_on_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'ensure_newline_before_comments': True, 'line_length': 88}, 'django': {'combine_as_imports': True, 'include_trailing_comma': True, 'multi_line_output': 5, 'line_length': 79}, 'pycharm': {'multi_line_output': 3, 'force_grid_wrap': 2, 'lines_after_imports': 2}, 'google': {'force_single_line': True, 'force_sort_within_sections': True, 'lexicographical': True, 'line_length': 1000, 'single_line_exclusions': ('collections.abc', 'six.moves', 'typing', 'typing_extensions'), 'order_by_type': False, 'group_by_package': True}, 'open_stack': {'force_single_line': True, 'force_sort_within_sections': True, 'lexicographical': True}, 'plone': {'multi_line_output': 3, 'include_trailing_comma': True, 'split_on_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'ensure_newline_before_comments': True, 'line_length': 88, 'force_alphabetical_sort': True, 'force_single_line': True, 'lines_after_imports': 2}, 'attrs': {'atomic': True, 'force_grid_wrap': 0, 'include_trailing_comma': True, 'lines_after_imports': 2, 'lines_between_types': 1, 'multi_line_output': 3, 'use_parentheses': True}, 'hug': {'multi_line_output': 3, 'include_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'line_length': 100}, 'wemake': {'multi_line_output': 3, 'include_trailing_comma': True, 'use_parentheses': True, 'line_length': 80}, 'appnexus': {'multi_line_output': 3, 'include_trailing_comma': True, 'split_on_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'ensure_newline_before_comments': True, 'line_length': 88, 'force_sort_within_sections': True, 'order_by_type': False, 'case_sensitive': False, 'reverse_relative': True, 'sort_relative_in_force_sorted_sections': True, 'sections': ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'APPLICATION', 'LOCALFOLDER'], 'no_lines_before': 'LOCALFOLDER'}}
    assert module_1.SECTION_DEFAULTS == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert module_1.FIRSTPARTY == 'FIRSTPARTY'
    assert module_1.FUTURE == 'FUTURE'
    assert module_1.LOCALFOLDER == 'LOCALFOLDER'
    assert module_1.STDLIB == 'STDLIB'
    assert module_1.THIRDPARTY == 'THIRDPARTY'
    assert f'{type(module_1.CYTHON_EXTENSIONS).__module__}.{type(module_1.CYTHON_EXTENSIONS).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.CYTHON_EXTENSIONS) == 2
    assert f'{type(module_1.SUPPORTED_EXTENSIONS).__module__}.{type(module_1.SUPPORTED_EXTENSIONS).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.SUPPORTED_EXTENSIONS) == 4
    assert f'{type(module_1.BLOCKED_EXTENSIONS).__module__}.{type(module_1.BLOCKED_EXTENSIONS).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.BLOCKED_EXTENSIONS) == 1
    assert module_1.FILE_SKIP_COMMENTS == ('isort:skip_file', 'isort: skip_file')
    assert module_1.MAX_CONFIG_SEARCH_DEPTH == 25
    assert module_1.STOP_CONFIG_SEARCH_ON_DIRS == ('.git', '.hg')
    assert module_1.VALID_PY_TARGETS == ('all', '2', '27', '3', '310', '311', '312', '313', '314', '36', '37', '38', '39')
    assert module_1.CONFIG_SOURCES == ('.isort.cfg', 'pyproject.toml', 'setup.cfg', 'tox.ini', '.editorconfig')
    assert f'{type(module_1.DEFAULT_SKIP).__module__}.{type(module_1.DEFAULT_SKIP).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_SKIP) == 19
    assert module_1.CONFIG_SECTIONS == {'.isort.cfg': ('settings', 'isort'), 'pyproject.toml': ('tool.isort',), 'setup.cfg': ('isort', 'tool:isort'), 'tox.ini': ('isort', 'tool:isort'), '.editorconfig': ('*', '*.py', '**.py', '*.{py}')}
    assert module_1.FALLBACK_CONFIG_SECTIONS == ('isort', 'tool:isort', 'tool.isort')
    assert module_1.IMPORT_HEADING_PREFIX == 'import_heading_'
    assert module_1.IMPORT_FOOTER_PREFIX == 'import_footer_'
    assert module_1.KNOWN_PREFIX == 'known_'
    assert module_1.KNOWN_SECTION_MAPPING == {'STDLIB': 'STANDARD_LIBRARY', 'FUTURE': 'FUTURE_LIBRARY', 'FIRSTPARTY': 'FIRST_PARTY', 'THIRDPARTY': 'THIRD_PARTY', 'LOCALFOLDER': 'LOCAL_FOLDER'}
    assert module_1.RUNTIME_SOURCE == 'runtime'
    assert module_1.DEPRECATED_SETTINGS == ('not_skip', 'keep_direct_and_as_imports')
    assert f'{type(module_1.DEFAULT_CONFIG).__module__}.{type(module_1.DEFAULT_CONFIG).__qualname__}' == 'isort.settings.Config'
    assert module_1.DEFAULT_CONFIG.py_version == 'py3'
    assert f'{type(module_1.DEFAULT_CONFIG.force_to_top).__module__}.{type(module_1.DEFAULT_CONFIG.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.force_to_top) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.skip).__module__}.{type(module_1.DEFAULT_CONFIG.skip).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.skip) == 19
    assert f'{type(module_1.DEFAULT_CONFIG.extend_skip).__module__}.{type(module_1.DEFAULT_CONFIG.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.extend_skip) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.skip_glob).__module__}.{type(module_1.DEFAULT_CONFIG.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.skip_glob) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.extend_skip_glob).__module__}.{type(module_1.DEFAULT_CONFIG.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.extend_skip_glob) == 0
    assert module_1.DEFAULT_CONFIG.skip_gitignore is False
    assert module_1.DEFAULT_CONFIG.line_length == 79
    assert module_1.DEFAULT_CONFIG.wrap_length == 0
    assert module_1.DEFAULT_CONFIG.line_ending == ''
    assert module_1.DEFAULT_CONFIG.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert module_1.DEFAULT_CONFIG.no_sections is False
    assert f'{type(module_1.DEFAULT_CONFIG.known_future_library).__module__}.{type(module_1.DEFAULT_CONFIG.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_future_library) == 1
    assert f'{type(module_1.DEFAULT_CONFIG.known_third_party).__module__}.{type(module_1.DEFAULT_CONFIG.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_third_party) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.known_first_party).__module__}.{type(module_1.DEFAULT_CONFIG.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_first_party) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.known_local_folder).__module__}.{type(module_1.DEFAULT_CONFIG.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_local_folder) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.known_standard_library).__module__}.{type(module_1.DEFAULT_CONFIG.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_standard_library) == 234
    assert f'{type(module_1.DEFAULT_CONFIG.extra_standard_library).__module__}.{type(module_1.DEFAULT_CONFIG.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.extra_standard_library) == 0
    assert module_1.DEFAULT_CONFIG.known_other == {}
    assert module_1.DEFAULT_CONFIG.multi_line_output == module_2.WrapModes.GRID
    assert module_1.DEFAULT_CONFIG.forced_separate == ()
    assert module_1.DEFAULT_CONFIG.indent == '    '
    assert module_1.DEFAULT_CONFIG.comment_prefix == '  #'
    assert module_1.DEFAULT_CONFIG.length_sort is False
    assert module_1.DEFAULT_CONFIG.length_sort_straight is False
    assert f'{type(module_1.DEFAULT_CONFIG.length_sort_sections).__module__}.{type(module_1.DEFAULT_CONFIG.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.length_sort_sections) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.add_imports).__module__}.{type(module_1.DEFAULT_CONFIG.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.add_imports) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.remove_imports).__module__}.{type(module_1.DEFAULT_CONFIG.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.remove_imports) == 0
    assert module_1.DEFAULT_CONFIG.append_only is False
    assert module_1.DEFAULT_CONFIG.reverse_relative is False
    assert module_1.DEFAULT_CONFIG.force_single_line is False
    assert module_1.DEFAULT_CONFIG.single_line_exclusions == ()
    assert module_1.DEFAULT_CONFIG.default_section == 'THIRDPARTY'
    assert module_1.DEFAULT_CONFIG.import_headings == {}
    assert module_1.DEFAULT_CONFIG.import_footers == {}
    assert module_1.DEFAULT_CONFIG.balanced_wrapping is False
    assert module_1.DEFAULT_CONFIG.use_parentheses is False
    assert module_1.DEFAULT_CONFIG.order_by_type is True
    assert module_1.DEFAULT_CONFIG.atomic is False
    assert module_1.DEFAULT_CONFIG.lines_before_imports == -1
    assert module_1.DEFAULT_CONFIG.lines_after_imports == -1
    assert module_1.DEFAULT_CONFIG.lines_between_sections == 1
    assert module_1.DEFAULT_CONFIG.lines_between_types == 0
    assert module_1.DEFAULT_CONFIG.combine_as_imports is False
    assert module_1.DEFAULT_CONFIG.combine_star is False
    assert module_1.DEFAULT_CONFIG.include_trailing_comma is False
    assert module_1.DEFAULT_CONFIG.from_first is False
    assert module_1.DEFAULT_CONFIG.verbose is False
    assert module_1.DEFAULT_CONFIG.quiet is False
    assert module_1.DEFAULT_CONFIG.force_adds is False
    assert module_1.DEFAULT_CONFIG.force_alphabetical_sort_within_sections is False
    assert module_1.DEFAULT_CONFIG.force_alphabetical_sort is False
    assert module_1.DEFAULT_CONFIG.force_grid_wrap == 0
    assert module_1.DEFAULT_CONFIG.force_sort_within_sections is False
    assert module_1.DEFAULT_CONFIG.lexicographical is False
    assert module_1.DEFAULT_CONFIG.group_by_package is False
    assert module_1.DEFAULT_CONFIG.ignore_whitespace is False
    assert f'{type(module_1.DEFAULT_CONFIG.no_lines_before).__module__}.{type(module_1.DEFAULT_CONFIG.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.no_lines_before) == 0
    assert module_1.DEFAULT_CONFIG.no_inline_sort is False
    assert module_1.DEFAULT_CONFIG.ignore_comments is False
    assert module_1.DEFAULT_CONFIG.case_sensitive is False
    assert f'{type(module_1.DEFAULT_CONFIG.sources).__module__}.{type(module_1.DEFAULT_CONFIG.sources).__qualname__}' == 'builtins.tuple'
    assert len(module_1.DEFAULT_CONFIG.sources) == 1
    assert module_1.DEFAULT_CONFIG.virtual_env == ''
    assert module_1.DEFAULT_CONFIG.conda_env == ''
    assert module_1.DEFAULT_CONFIG.ensure_newline_before_comments is False
    assert module_1.DEFAULT_CONFIG.directory == '/workspace'
    assert module_1.DEFAULT_CONFIG.profile == ''
    assert module_1.DEFAULT_CONFIG.honor_noqa is False
    assert f'{type(module_1.DEFAULT_CONFIG.src_paths).__module__}.{type(module_1.DEFAULT_CONFIG.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(module_1.DEFAULT_CONFIG.src_paths) == 2
    assert module_1.DEFAULT_CONFIG.remove_redundant_aliases is False
    assert module_1.DEFAULT_CONFIG.float_to_top is False
    assert module_1.DEFAULT_CONFIG.filter_files is False
    assert module_1.DEFAULT_CONFIG.formatter == ''
    assert module_1.DEFAULT_CONFIG.formatting_function is None
    assert module_1.DEFAULT_CONFIG.color_output is False
    assert f'{type(module_1.DEFAULT_CONFIG.treat_comments_as_code).__module__}.{type(module_1.DEFAULT_CONFIG.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.treat_comments_as_code) == 0
    assert module_1.DEFAULT_CONFIG.treat_all_comments_as_code is False
    assert f'{type(module_1.DEFAULT_CONFIG.supported_extensions).__module__}.{type(module_1.DEFAULT_CONFIG.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.supported_extensions) == 4
    assert f'{type(module_1.DEFAULT_CONFIG.blocked_extensions).__module__}.{type(module_1.DEFAULT_CONFIG.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.blocked_extensions) == 1
    assert f'{type(module_1.DEFAULT_CONFIG.constants).__module__}.{type(module_1.DEFAULT_CONFIG.constants).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.constants) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.classes).__module__}.{type(module_1.DEFAULT_CONFIG.classes).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.classes) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.variables).__module__}.{type(module_1.DEFAULT_CONFIG.variables).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.variables) == 0
    assert module_1.DEFAULT_CONFIG.dedup_headings is False
    assert module_1.DEFAULT_CONFIG.only_sections is False
    assert module_1.DEFAULT_CONFIG.only_modified is False
    assert module_1.DEFAULT_CONFIG.combine_straight_imports is False
    assert module_1.DEFAULT_CONFIG.auto_identify_namespace_packages is True
    assert f'{type(module_1.DEFAULT_CONFIG.namespace_packages).__module__}.{type(module_1.DEFAULT_CONFIG.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.namespace_packages) == 0
    assert module_1.DEFAULT_CONFIG.follow_links is True
    assert module_1.DEFAULT_CONFIG.indented_import_headings is True
    assert module_1.DEFAULT_CONFIG.honor_case_in_force_sorted_sections is False
    assert module_1.DEFAULT_CONFIG.sort_relative_in_force_sorted_sections is False
    assert module_1.DEFAULT_CONFIG.overwrite_in_place is False
    assert module_1.DEFAULT_CONFIG.reverse_sort is False
    assert module_1.DEFAULT_CONFIG.star_first is False
    assert module_1.DEFAULT_CONFIG.git_ls_files == {}
    assert module_1.DEFAULT_CONFIG.format_error == '{error}: {message}'
    assert module_1.DEFAULT_CONFIG.format_success == '{success}: {message}'
    assert module_1.DEFAULT_CONFIG.sort_order == 'natural'
    assert module_1.DEFAULT_CONFIG.sort_reexports is False
    assert module_1.DEFAULT_CONFIG.split_on_trailing_comma is False
    assert f'{type(module_1.Config.known_patterns).__module__}.{type(module_1.Config.known_patterns).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.section_comments).__module__}.{type(module_1.Config.section_comments).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.section_comments_end).__module__}.{type(module_1.Config.section_comments_end).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.skips).__module__}.{type(module_1.Config.skips).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.skip_globs).__module__}.{type(module_1.Config.skip_globs).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.sorting_function).__module__}.{type(module_1.Config.sorting_function).__qualname__}' == 'builtins.property'
    var_2 = module_0.find(var_0, var_1, var_0, var_0)
    var_3 = list(var_2)
    var_4 = 'fle2.py'
    var_5 = []
    var_6 = module_0.find(var_4, var_5, var_5, var_3)
    with pytest.raises(AttributeError):
        var_7 = list(var_6)

def test_case_3():
    var_0 = module_1.Config()
    assert f'{type(var_0).__module__}.{type(var_0).__qualname__}' == 'isort.settings.Config'
    assert var_0.py_version == 'py3'
    assert f'{type(var_0.force_to_top).__module__}.{type(var_0.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.force_to_top) == 0
    assert f'{type(var_0.skip).__module__}.{type(var_0.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.skip) == 19
    assert f'{type(var_0.extend_skip).__module__}.{type(var_0.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.extend_skip) == 0
    assert f'{type(var_0.skip_glob).__module__}.{type(var_0.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.skip_glob) == 0
    assert f'{type(var_0.extend_skip_glob).__module__}.{type(var_0.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.extend_skip_glob) == 0
    assert var_0.skip_gitignore is False
    assert var_0.line_length == 79
    assert var_0.wrap_length == 0
    assert var_0.line_ending == ''
    assert var_0.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_0.no_sections is False
    assert f'{type(var_0.known_future_library).__module__}.{type(var_0.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.known_future_library) == 1
    assert f'{type(var_0.known_third_party).__module__}.{type(var_0.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.known_third_party) == 0
    assert f'{type(var_0.known_first_party).__module__}.{type(var_0.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.known_first_party) == 0
    assert f'{type(var_0.known_local_folder).__module__}.{type(var_0.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.known_local_folder) == 0
    assert f'{type(var_0.known_standard_library).__module__}.{type(var_0.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.known_standard_library) == 234
    assert f'{type(var_0.extra_standard_library).__module__}.{type(var_0.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.extra_standard_library) == 0
    assert var_0.known_other == {}
    assert var_0.multi_line_output == module_2.WrapModes.GRID
    assert var_0.forced_separate == ()
    assert var_0.indent == '    '
    assert var_0.comment_prefix == '  #'
    assert var_0.length_sort is False
    assert var_0.length_sort_straight is False
    assert f'{type(var_0.length_sort_sections).__module__}.{type(var_0.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.length_sort_sections) == 0
    assert f'{type(var_0.add_imports).__module__}.{type(var_0.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.add_imports) == 0
    assert f'{type(var_0.remove_imports).__module__}.{type(var_0.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.remove_imports) == 0
    assert var_0.append_only is False
    assert var_0.reverse_relative is False
    assert var_0.force_single_line is False
    assert var_0.single_line_exclusions == ()
    assert var_0.default_section == 'THIRDPARTY'
    assert var_0.import_headings == {}
    assert var_0.import_footers == {}
    assert var_0.balanced_wrapping is False
    assert var_0.use_parentheses is False
    assert var_0.order_by_type is True
    assert var_0.atomic is False
    assert var_0.lines_before_imports == -1
    assert var_0.lines_after_imports == -1
    assert var_0.lines_between_sections == 1
    assert var_0.lines_between_types == 0
    assert var_0.combine_as_imports is False
    assert var_0.combine_star is False
    assert var_0.include_trailing_comma is False
    assert var_0.from_first is False
    assert var_0.verbose is False
    assert var_0.quiet is False
    assert var_0.force_adds is False
    assert var_0.force_alphabetical_sort_within_sections is False
    assert var_0.force_alphabetical_sort is False
    assert var_0.force_grid_wrap == 0
    assert var_0.force_sort_within_sections is False
    assert var_0.lexicographical is False
    assert var_0.group_by_package is False
    assert var_0.ignore_whitespace is False
    assert f'{type(var_0.no_lines_before).__module__}.{type(var_0.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.no_lines_before) == 0
    assert var_0.no_inline_sort is False
    assert var_0.ignore_comments is False
    assert var_0.case_sensitive is False
    assert f'{type(var_0.sources).__module__}.{type(var_0.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_0.sources) == 1
    assert var_0.virtual_env == ''
    assert var_0.conda_env == ''
    assert var_0.ensure_newline_before_comments is False
    assert var_0.directory == '/workspace'
    assert var_0.profile == ''
    assert var_0.honor_noqa is False
    assert f'{type(var_0.src_paths).__module__}.{type(var_0.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_0.src_paths) == 2
    assert var_0.remove_redundant_aliases is False
    assert var_0.float_to_top is False
    assert var_0.filter_files is False
    assert var_0.formatter == ''
    assert var_0.formatting_function is None
    assert var_0.color_output is False
    assert f'{type(var_0.treat_comments_as_code).__module__}.{type(var_0.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.treat_comments_as_code) == 0
    assert var_0.treat_all_comments_as_code is False
    assert f'{type(var_0.supported_extensions).__module__}.{type(var_0.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.supported_extensions) == 4
    assert f'{type(var_0.blocked_extensions).__module__}.{type(var_0.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.blocked_extensions) == 1
    assert f'{type(var_0.constants).__module__}.{type(var_0.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.constants) == 0
    assert f'{type(var_0.classes).__module__}.{type(var_0.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.classes) == 0
    assert f'{type(var_0.variables).__module__}.{type(var_0.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.variables) == 0
    assert var_0.dedup_headings is False
    assert var_0.only_sections is False
    assert var_0.only_modified is False
    assert var_0.combine_straight_imports is False
    assert var_0.auto_identify_namespace_packages is True
    assert f'{type(var_0.namespace_packages).__module__}.{type(var_0.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_0.namespace_packages) == 0
    assert var_0.follow_links is True
    assert var_0.indented_import_headings is True
    assert var_0.honor_case_in_force_sorted_sections is False
    assert var_0.sort_relative_in_force_sorted_sections is False
    assert var_0.overwrite_in_place is False
    assert var_0.reverse_sort is False
    assert var_0.star_first is False
    assert var_0.git_ls_files == {}
    assert var_0.format_error == '{error}: {message}'
    assert var_0.format_success == '{success}: {message}'
    assert var_0.sort_order == 'natural'
    assert var_0.sort_reexports is False
    assert var_0.split_on_trailing_comma is False
    assert module_1.TYPE_CHECKING is False
    assert module_1.profiles == {'black': {'multi_line_output': 3, 'include_trailing_comma': True, 'split_on_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'ensure_newline_before_comments': True, 'line_length': 88}, 'django': {'combine_as_imports': True, 'include_trailing_comma': True, 'multi_line_output': 5, 'line_length': 79}, 'pycharm': {'multi_line_output': 3, 'force_grid_wrap': 2, 'lines_after_imports': 2}, 'google': {'force_single_line': True, 'force_sort_within_sections': True, 'lexicographical': True, 'line_length': 1000, 'single_line_exclusions': ('collections.abc', 'six.moves', 'typing', 'typing_extensions'), 'order_by_type': False, 'group_by_package': True}, 'open_stack': {'force_single_line': True, 'force_sort_within_sections': True, 'lexicographical': True}, 'plone': {'multi_line_output': 3, 'include_trailing_comma': True, 'split_on_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'ensure_newline_before_comments': True, 'line_length': 88, 'force_alphabetical_sort': True, 'force_single_line': True, 'lines_after_imports': 2}, 'attrs': {'atomic': True, 'force_grid_wrap': 0, 'include_trailing_comma': True, 'lines_after_imports': 2, 'lines_between_types': 1, 'multi_line_output': 3, 'use_parentheses': True}, 'hug': {'multi_line_output': 3, 'include_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'line_length': 100}, 'wemake': {'multi_line_output': 3, 'include_trailing_comma': True, 'use_parentheses': True, 'line_length': 80}, 'appnexus': {'multi_line_output': 3, 'include_trailing_comma': True, 'split_on_trailing_comma': True, 'force_grid_wrap': 0, 'use_parentheses': True, 'ensure_newline_before_comments': True, 'line_length': 88, 'force_sort_within_sections': True, 'order_by_type': False, 'case_sensitive': False, 'reverse_relative': True, 'sort_relative_in_force_sorted_sections': True, 'sections': ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'APPLICATION', 'LOCALFOLDER'], 'no_lines_before': 'LOCALFOLDER'}}
    assert module_1.SECTION_DEFAULTS == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert module_1.FIRSTPARTY == 'FIRSTPARTY'
    assert module_1.FUTURE == 'FUTURE'
    assert module_1.LOCALFOLDER == 'LOCALFOLDER'
    assert module_1.STDLIB == 'STDLIB'
    assert module_1.THIRDPARTY == 'THIRDPARTY'
    assert f'{type(module_1.CYTHON_EXTENSIONS).__module__}.{type(module_1.CYTHON_EXTENSIONS).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.CYTHON_EXTENSIONS) == 2
    assert f'{type(module_1.SUPPORTED_EXTENSIONS).__module__}.{type(module_1.SUPPORTED_EXTENSIONS).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.SUPPORTED_EXTENSIONS) == 4
    assert f'{type(module_1.BLOCKED_EXTENSIONS).__module__}.{type(module_1.BLOCKED_EXTENSIONS).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.BLOCKED_EXTENSIONS) == 1
    assert module_1.FILE_SKIP_COMMENTS == ('isort:skip_file', 'isort: skip_file')
    assert module_1.MAX_CONFIG_SEARCH_DEPTH == 25
    assert module_1.STOP_CONFIG_SEARCH_ON_DIRS == ('.git', '.hg')
    assert module_1.VALID_PY_TARGETS == ('all', '2', '27', '3', '310', '311', '312', '313', '314', '36', '37', '38', '39')
    assert module_1.CONFIG_SOURCES == ('.isort.cfg', 'pyproject.toml', 'setup.cfg', 'tox.ini', '.editorconfig')
    assert f'{type(module_1.DEFAULT_SKIP).__module__}.{type(module_1.DEFAULT_SKIP).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_SKIP) == 19
    assert module_1.CONFIG_SECTIONS == {'.isort.cfg': ('settings', 'isort'), 'pyproject.toml': ('tool.isort',), 'setup.cfg': ('isort', 'tool:isort'), 'tox.ini': ('isort', 'tool:isort'), '.editorconfig': ('*', '*.py', '**.py', '*.{py}')}
    assert module_1.FALLBACK_CONFIG_SECTIONS == ('isort', 'tool:isort', 'tool.isort')
    assert module_1.IMPORT_HEADING_PREFIX == 'import_heading_'
    assert module_1.IMPORT_FOOTER_PREFIX == 'import_footer_'
    assert module_1.KNOWN_PREFIX == 'known_'
    assert module_1.KNOWN_SECTION_MAPPING == {'STDLIB': 'STANDARD_LIBRARY', 'FUTURE': 'FUTURE_LIBRARY', 'FIRSTPARTY': 'FIRST_PARTY', 'THIRDPARTY': 'THIRD_PARTY', 'LOCALFOLDER': 'LOCAL_FOLDER'}
    assert module_1.RUNTIME_SOURCE == 'runtime'
    assert module_1.DEPRECATED_SETTINGS == ('not_skip', 'keep_direct_and_as_imports')
    assert f'{type(module_1.DEFAULT_CONFIG).__module__}.{type(module_1.DEFAULT_CONFIG).__qualname__}' == 'isort.settings.Config'
    assert module_1.DEFAULT_CONFIG.py_version == 'py3'
    assert f'{type(module_1.DEFAULT_CONFIG.force_to_top).__module__}.{type(module_1.DEFAULT_CONFIG.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.force_to_top) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.skip).__module__}.{type(module_1.DEFAULT_CONFIG.skip).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.skip) == 19
    assert f'{type(module_1.DEFAULT_CONFIG.extend_skip).__module__}.{type(module_1.DEFAULT_CONFIG.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.extend_skip) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.skip_glob).__module__}.{type(module_1.DEFAULT_CONFIG.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.skip_glob) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.extend_skip_glob).__module__}.{type(module_1.DEFAULT_CONFIG.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.extend_skip_glob) == 0
    assert module_1.DEFAULT_CONFIG.skip_gitignore is False
    assert module_1.DEFAULT_CONFIG.line_length == 79
    assert module_1.DEFAULT_CONFIG.wrap_length == 0
    assert module_1.DEFAULT_CONFIG.line_ending == ''
    assert module_1.DEFAULT_CONFIG.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert module_1.DEFAULT_CONFIG.no_sections is False
    assert f'{type(module_1.DEFAULT_CONFIG.known_future_library).__module__}.{type(module_1.DEFAULT_CONFIG.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_future_library) == 1
    assert f'{type(module_1.DEFAULT_CONFIG.known_third_party).__module__}.{type(module_1.DEFAULT_CONFIG.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_third_party) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.known_first_party).__module__}.{type(module_1.DEFAULT_CONFIG.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_first_party) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.known_local_folder).__module__}.{type(module_1.DEFAULT_CONFIG.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_local_folder) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.known_standard_library).__module__}.{type(module_1.DEFAULT_CONFIG.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.known_standard_library) == 234
    assert f'{type(module_1.DEFAULT_CONFIG.extra_standard_library).__module__}.{type(module_1.DEFAULT_CONFIG.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.extra_standard_library) == 0
    assert module_1.DEFAULT_CONFIG.known_other == {}
    assert module_1.DEFAULT_CONFIG.multi_line_output == module_2.WrapModes.GRID
    assert module_1.DEFAULT_CONFIG.forced_separate == ()
    assert module_1.DEFAULT_CONFIG.indent == '    '
    assert module_1.DEFAULT_CONFIG.comment_prefix == '  #'
    assert module_1.DEFAULT_CONFIG.length_sort is False
    assert module_1.DEFAULT_CONFIG.length_sort_straight is False
    assert f'{type(module_1.DEFAULT_CONFIG.length_sort_sections).__module__}.{type(module_1.DEFAULT_CONFIG.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.length_sort_sections) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.add_imports).__module__}.{type(module_1.DEFAULT_CONFIG.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.add_imports) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.remove_imports).__module__}.{type(module_1.DEFAULT_CONFIG.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.remove_imports) == 0
    assert module_1.DEFAULT_CONFIG.append_only is False
    assert module_1.DEFAULT_CONFIG.reverse_relative is False
    assert module_1.DEFAULT_CONFIG.force_single_line is False
    assert module_1.DEFAULT_CONFIG.single_line_exclusions == ()
    assert module_1.DEFAULT_CONFIG.default_section == 'THIRDPARTY'
    assert module_1.DEFAULT_CONFIG.import_headings == {}
    assert module_1.DEFAULT_CONFIG.import_footers == {}
    assert module_1.DEFAULT_CONFIG.balanced_wrapping is False
    assert module_1.DEFAULT_CONFIG.use_parentheses is False
    assert module_1.DEFAULT_CONFIG.order_by_type is True
    assert module_1.DEFAULT_CONFIG.atomic is False
    assert module_1.DEFAULT_CONFIG.lines_before_imports == -1
    assert module_1.DEFAULT_CONFIG.lines_after_imports == -1
    assert module_1.DEFAULT_CONFIG.lines_between_sections == 1
    assert module_1.DEFAULT_CONFIG.lines_between_types == 0
    assert module_1.DEFAULT_CONFIG.combine_as_imports is False
    assert module_1.DEFAULT_CONFIG.combine_star is False
    assert module_1.DEFAULT_CONFIG.include_trailing_comma is False
    assert module_1.DEFAULT_CONFIG.from_first is False
    assert module_1.DEFAULT_CONFIG.verbose is False
    assert module_1.DEFAULT_CONFIG.quiet is False
    assert module_1.DEFAULT_CONFIG.force_adds is False
    assert module_1.DEFAULT_CONFIG.force_alphabetical_sort_within_sections is False
    assert module_1.DEFAULT_CONFIG.force_alphabetical_sort is False
    assert module_1.DEFAULT_CONFIG.force_grid_wrap == 0
    assert module_1.DEFAULT_CONFIG.force_sort_within_sections is False
    assert module_1.DEFAULT_CONFIG.lexicographical is False
    assert module_1.DEFAULT_CONFIG.group_by_package is False
    assert module_1.DEFAULT_CONFIG.ignore_whitespace is False
    assert f'{type(module_1.DEFAULT_CONFIG.no_lines_before).__module__}.{type(module_1.DEFAULT_CONFIG.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.no_lines_before) == 0
    assert module_1.DEFAULT_CONFIG.no_inline_sort is False
    assert module_1.DEFAULT_CONFIG.ignore_comments is False
    assert module_1.DEFAULT_CONFIG.case_sensitive is False
    assert f'{type(module_1.DEFAULT_CONFIG.sources).__module__}.{type(module_1.DEFAULT_CONFIG.sources).__qualname__}' == 'builtins.tuple'
    assert len(module_1.DEFAULT_CONFIG.sources) == 1
    assert module_1.DEFAULT_CONFIG.virtual_env == ''
    assert module_1.DEFAULT_CONFIG.conda_env == ''
    assert module_1.DEFAULT_CONFIG.ensure_newline_before_comments is False
    assert module_1.DEFAULT_CONFIG.directory == '/workspace'
    assert module_1.DEFAULT_CONFIG.profile == ''
    assert module_1.DEFAULT_CONFIG.honor_noqa is False
    assert f'{type(module_1.DEFAULT_CONFIG.src_paths).__module__}.{type(module_1.DEFAULT_CONFIG.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(module_1.DEFAULT_CONFIG.src_paths) == 2
    assert module_1.DEFAULT_CONFIG.remove_redundant_aliases is False
    assert module_1.DEFAULT_CONFIG.float_to_top is False
    assert module_1.DEFAULT_CONFIG.filter_files is False
    assert module_1.DEFAULT_CONFIG.formatter == ''
    assert module_1.DEFAULT_CONFIG.formatting_function is None
    assert module_1.DEFAULT_CONFIG.color_output is False
    assert f'{type(module_1.DEFAULT_CONFIG.treat_comments_as_code).__module__}.{type(module_1.DEFAULT_CONFIG.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.treat_comments_as_code) == 0
    assert module_1.DEFAULT_CONFIG.treat_all_comments_as_code is False
    assert f'{type(module_1.DEFAULT_CONFIG.supported_extensions).__module__}.{type(module_1.DEFAULT_CONFIG.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.supported_extensions) == 4
    assert f'{type(module_1.DEFAULT_CONFIG.blocked_extensions).__module__}.{type(module_1.DEFAULT_CONFIG.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.blocked_extensions) == 1
    assert f'{type(module_1.DEFAULT_CONFIG.constants).__module__}.{type(module_1.DEFAULT_CONFIG.constants).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.constants) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.classes).__module__}.{type(module_1.DEFAULT_CONFIG.classes).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.classes) == 0
    assert f'{type(module_1.DEFAULT_CONFIG.variables).__module__}.{type(module_1.DEFAULT_CONFIG.variables).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.variables) == 0
    assert module_1.DEFAULT_CONFIG.dedup_headings is False
    assert module_1.DEFAULT_CONFIG.only_sections is False
    assert module_1.DEFAULT_CONFIG.only_modified is False
    assert module_1.DEFAULT_CONFIG.combine_straight_imports is False
    assert module_1.DEFAULT_CONFIG.auto_identify_namespace_packages is True
    assert f'{type(module_1.DEFAULT_CONFIG.namespace_packages).__module__}.{type(module_1.DEFAULT_CONFIG.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(module_1.DEFAULT_CONFIG.namespace_packages) == 0
    assert module_1.DEFAULT_CONFIG.follow_links is True
    assert module_1.DEFAULT_CONFIG.indented_import_headings is True
    assert module_1.DEFAULT_CONFIG.honor_case_in_force_sorted_sections is False
    assert module_1.DEFAULT_CONFIG.sort_relative_in_force_sorted_sections is False
    assert module_1.DEFAULT_CONFIG.overwrite_in_place is False
    assert module_1.DEFAULT_CONFIG.reverse_sort is False
    assert module_1.DEFAULT_CONFIG.star_first is False
    assert module_1.DEFAULT_CONFIG.git_ls_files == {}
    assert module_1.DEFAULT_CONFIG.format_error == '{error}: {message}'
    assert module_1.DEFAULT_CONFIG.format_success == '{success}: {message}'
    assert module_1.DEFAULT_CONFIG.sort_order == 'natural'
    assert module_1.DEFAULT_CONFIG.sort_reexports is False
    assert module_1.DEFAULT_CONFIG.split_on_trailing_comma is False
    assert f'{type(module_1.Config.known_patterns).__module__}.{type(module_1.Config.known_patterns).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.section_comments).__module__}.{type(module_1.Config.section_comments).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.section_comments_end).__module__}.{type(module_1.Config.section_comments_end).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.skips).__module__}.{type(module_1.Config.skips).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.skip_globs).__module__}.{type(module_1.Config.skip_globs).__qualname__}' == 'builtins.property'
    assert f'{type(module_1.Config.sorting_function).__module__}.{type(module_1.Config.sorting_function).__qualname__}' == 'builtins.property'
    var_1 = []
    var_2 = 'not_python.txt'
    var_3 = module_1.Config()
    assert f'{type(var_3).__module__}.{type(var_3).__qualname__}' == 'isort.settings.Config'
    assert var_3.py_version == 'py3'
    assert f'{type(var_3.force_to_top).__module__}.{type(var_3.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.force_to_top) == 0
    assert f'{type(var_3.skip).__module__}.{type(var_3.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.skip) == 19
    assert f'{type(var_3.extend_skip).__module__}.{type(var_3.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.extend_skip) == 0
    assert f'{type(var_3.skip_glob).__module__}.{type(var_3.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.skip_glob) == 0
    assert f'{type(var_3.extend_skip_glob).__module__}.{type(var_3.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.extend_skip_glob) == 0
    assert var_3.skip_gitignore is False
    assert var_3.line_length == 79
    assert var_3.wrap_length == 0
    assert var_3.line_ending == ''
    assert var_3.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_3.no_sections is False
    assert f'{type(var_3.known_future_library).__module__}.{type(var_3.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.known_future_library) == 1
    assert f'{type(var_3.known_third_party).__module__}.{type(var_3.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.known_third_party) == 0
    assert f'{type(var_3.known_first_party).__module__}.{type(var_3.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.known_first_party) == 0
    assert f'{type(var_3.known_local_folder).__module__}.{type(var_3.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.known_local_folder) == 0
    assert f'{type(var_3.known_standard_library).__module__}.{type(var_3.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.known_standard_library) == 234
    assert f'{type(var_3.extra_standard_library).__module__}.{type(var_3.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.extra_standard_library) == 0
    assert var_3.known_other == {}
    assert var_3.multi_line_output == module_2.WrapModes.GRID
    assert var_3.forced_separate == ()
    assert var_3.indent == '    '
    assert var_3.comment_prefix == '  #'
    assert var_3.length_sort is False
    assert var_3.length_sort_straight is False
    assert f'{type(var_3.length_sort_sections).__module__}.{type(var_3.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.length_sort_sections) == 0
    assert f'{type(var_3.add_imports).__module__}.{type(var_3.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.add_imports) == 0
    assert f'{type(var_3.remove_imports).__module__}.{type(var_3.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.remove_imports) == 0
    assert var_3.append_only is False
    assert var_3.reverse_relative is False
    assert var_3.force_single_line is False
    assert var_3.single_line_exclusions == ()
    assert var_3.default_section == 'THIRDPARTY'
    assert var_3.import_headings == {}
    assert var_3.import_footers == {}
    assert var_3.balanced_wrapping is False
    assert var_3.use_parentheses is False
    assert var_3.order_by_type is True
    assert var_3.atomic is False
    assert var_3.lines_before_imports == -1
    assert var_3.lines_after_imports == -1
    assert var_3.lines_between_sections == 1
    assert var_3.lines_between_types == 0
    assert var_3.combine_as_imports is False
    assert var_3.combine_star is False
    assert var_3.include_trailing_comma is False
    assert var_3.from_first is False
    assert var_3.verbose is False
    assert var_3.quiet is False
    assert var_3.force_adds is False
    assert var_3.force_alphabetical_sort_within_sections is False
    assert var_3.force_alphabetical_sort is False
    assert var_3.force_grid_wrap == 0
    assert var_3.force_sort_within_sections is False
    assert var_3.lexicographical is False
    assert var_3.group_by_package is False
    assert var_3.ignore_whitespace is False
    assert f'{type(var_3.no_lines_before).__module__}.{type(var_3.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.no_lines_before) == 0
    assert var_3.no_inline_sort is False
    assert var_3.ignore_comments is False
    assert var_3.case_sensitive is False
    assert f'{type(var_3.sources).__module__}.{type(var_3.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_3.sources) == 1
    assert var_3.virtual_env == ''
    assert var_3.conda_env == ''
    assert var_3.ensure_newline_before_comments is False
    assert var_3.directory == '/workspace'
    assert var_3.profile == ''
    assert var_3.honor_noqa is False
    assert f'{type(var_3.src_paths).__module__}.{type(var_3.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_3.src_paths) == 2
    assert var_3.remove_redundant_aliases is False
    assert var_3.float_to_top is False
    assert var_3.filter_files is False
    assert var_3.formatter == ''
    assert var_3.formatting_function is None
    assert var_3.color_output is False
    assert f'{type(var_3.treat_comments_as_code).__module__}.{type(var_3.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.treat_comments_as_code) == 0
    assert var_3.treat_all_comments_as_code is False
    assert f'{type(var_3.supported_extensions).__module__}.{type(var_3.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.supported_extensions) == 4
    assert f'{type(var_3.blocked_extensions).__module__}.{type(var_3.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.blocked_extensions) == 1
    assert f'{type(var_3.constants).__module__}.{type(var_3.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.constants) == 0
    assert f'{type(var_3.classes).__module__}.{type(var_3.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.classes) == 0
    assert f'{type(var_3.variables).__module__}.{type(var_3.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.variables) == 0
    assert var_3.dedup_headings is False
    assert var_3.only_sections is False
    assert var_3.only_modified is False
    assert var_3.combine_straight_imports is False
    assert var_3.auto_identify_namespace_packages is True
    assert f'{type(var_3.namespace_packages).__module__}.{type(var_3.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_3.namespace_packages) == 0
    assert var_3.follow_links is True
    assert var_3.indented_import_headings is True
    assert var_3.honor_case_in_force_sorted_sections is False
    assert var_3.sort_relative_in_force_sorted_sections is False
    assert var_3.overwrite_in_place is False
    assert var_3.reverse_sort is False
    assert var_3.star_first is False
    assert var_3.git_ls_files == {}
    assert var_3.format_error == '{error}: {message}'
    assert var_3.format_success == '{success}: {message}'
    assert var_3.sort_order == 'natural'
    assert var_3.sort_reexports is False
    assert var_3.split_on_trailing_comma is False
    var_4 = module_1.Config()
    assert f'{type(var_4).__module__}.{type(var_4).__qualname__}' == 'isort.settings.Config'
    assert var_4.py_version == 'py3'
    assert f'{type(var_4.force_to_top).__module__}.{type(var_4.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.force_to_top) == 0
    assert f'{type(var_4.skip).__module__}.{type(var_4.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.skip) == 19
    assert f'{type(var_4.extend_skip).__module__}.{type(var_4.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.extend_skip) == 0
    assert f'{type(var_4.skip_glob).__module__}.{type(var_4.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.skip_glob) == 0
    assert f'{type(var_4.extend_skip_glob).__module__}.{type(var_4.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.extend_skip_glob) == 0
    assert var_4.skip_gitignore is False
    assert var_4.line_length == 79
    assert var_4.wrap_length == 0
    assert var_4.line_ending == ''
    assert var_4.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_4.no_sections is False
    assert f'{type(var_4.known_future_library).__module__}.{type(var_4.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.known_future_library) == 1
    assert f'{type(var_4.known_third_party).__module__}.{type(var_4.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.known_third_party) == 0
    assert f'{type(var_4.known_first_party).__module__}.{type(var_4.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.known_first_party) == 0
    assert f'{type(var_4.known_local_folder).__module__}.{type(var_4.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.known_local_folder) == 0
    assert f'{type(var_4.known_standard_library).__module__}.{type(var_4.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.known_standard_library) == 234
    assert f'{type(var_4.extra_standard_library).__module__}.{type(var_4.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.extra_standard_library) == 0
    assert var_4.known_other == {}
    assert var_4.multi_line_output == module_2.WrapModes.GRID
    assert var_4.forced_separate == ()
    assert var_4.indent == '    '
    assert var_4.comment_prefix == '  #'
    assert var_4.length_sort is False
    assert var_4.length_sort_straight is False
    assert f'{type(var_4.length_sort_sections).__module__}.{type(var_4.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.length_sort_sections) == 0
    assert f'{type(var_4.add_imports).__module__}.{type(var_4.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.add_imports) == 0
    assert f'{type(var_4.remove_imports).__module__}.{type(var_4.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.remove_imports) == 0
    assert var_4.append_only is False
    assert var_4.reverse_relative is False
    assert var_4.force_single_line is False
    assert var_4.single_line_exclusions == ()
    assert var_4.default_section == 'THIRDPARTY'
    assert var_4.import_headings == {}
    assert var_4.import_footers == {}
    assert var_4.balanced_wrapping is False
    assert var_4.use_parentheses is False
    assert var_4.order_by_type is True
    assert var_4.atomic is False
    assert var_4.lines_before_imports == -1
    assert var_4.lines_after_imports == -1
    assert var_4.lines_between_sections == 1
    assert var_4.lines_between_types == 0
    assert var_4.combine_as_imports is False
    assert var_4.combine_star is False
    assert var_4.include_trailing_comma is False
    assert var_4.from_first is False
    assert var_4.verbose is False
    assert var_4.quiet is False
    assert var_4.force_adds is False
    assert var_4.force_alphabetical_sort_within_sections is False
    assert var_4.force_alphabetical_sort is False
    assert var_4.force_grid_wrap == 0
    assert var_4.force_sort_within_sections is False
    assert var_4.lexicographical is False
    assert var_4.group_by_package is False
    assert var_4.ignore_whitespace is False
    assert f'{type(var_4.no_lines_before).__module__}.{type(var_4.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.no_lines_before) == 0
    assert var_4.no_inline_sort is False
    assert var_4.ignore_comments is False
    assert var_4.case_sensitive is False
    assert f'{type(var_4.sources).__module__}.{type(var_4.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_4.sources) == 1
    assert var_4.virtual_env == ''
    assert var_4.conda_env == ''
    assert var_4.ensure_newline_before_comments is False
    assert var_4.directory == '/workspace'
    assert var_4.profile == ''
    assert var_4.honor_noqa is False
    assert f'{type(var_4.src_paths).__module__}.{type(var_4.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_4.src_paths) == 2
    assert var_4.remove_redundant_aliases is False
    assert var_4.float_to_top is False
    assert var_4.filter_files is False
    assert var_4.formatter == ''
    assert var_4.formatting_function is None
    assert var_4.color_output is False
    assert f'{type(var_4.treat_comments_as_code).__module__}.{type(var_4.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.treat_comments_as_code) == 0
    assert var_4.treat_all_comments_as_code is False
    assert f'{type(var_4.supported_extensions).__module__}.{type(var_4.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.supported_extensions) == 4
    assert f'{type(var_4.blocked_extensions).__module__}.{type(var_4.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.blocked_extensions) == 1
    assert f'{type(var_4.constants).__module__}.{type(var_4.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.constants) == 0
    assert f'{type(var_4.classes).__module__}.{type(var_4.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.classes) == 0
    assert f'{type(var_4.variables).__module__}.{type(var_4.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.variables) == 0
    assert var_4.dedup_headings is False
    assert var_4.only_sections is False
    assert var_4.only_modified is False
    assert var_4.combine_straight_imports is False
    assert var_4.auto_identify_namespace_packages is True
    assert f'{type(var_4.namespace_packages).__module__}.{type(var_4.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_4.namespace_packages) == 0
    assert var_4.follow_links is True
    assert var_4.indented_import_headings is True
    assert var_4.honor_case_in_force_sorted_sections is False
    assert var_4.sort_relative_in_force_sorted_sections is False
    assert var_4.overwrite_in_place is False
    assert var_4.reverse_sort is False
    assert var_4.star_first is False
    assert var_4.git_ls_files == {}
    assert var_4.format_error == '{error}: {message}'
    assert var_4.format_success == '{success}: {message}'
    assert var_4.sort_order == 'natural'
    assert var_4.sort_reexports is False
    assert var_4.split_on_trailing_comma is False
    var_5 = []
    var_6 = []
    var_7 = '/non/existent/file.py'
    var_8 = [var_7]
    var_9 = module_0.find(var_8, var_4, var_5, var_6)
    var_10 = list(var_9)
    var_11 = len(var_10)
    assert var_11 == 0
    var_12 = 'skipme'
    var_13 = [var_12]
    var_14 = module_1.Config()
    assert f'{type(var_14).__module__}.{type(var_14).__qualname__}' == 'isort.settings.Config'
    assert var_14.py_version == 'py3'
    assert f'{type(var_14.force_to_top).__module__}.{type(var_14.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.force_to_top) == 0
    assert f'{type(var_14.skip).__module__}.{type(var_14.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.skip) == 19
    assert f'{type(var_14.extend_skip).__module__}.{type(var_14.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.extend_skip) == 0
    assert f'{type(var_14.skip_glob).__module__}.{type(var_14.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.skip_glob) == 0
    assert f'{type(var_14.extend_skip_glob).__module__}.{type(var_14.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.extend_skip_glob) == 0
    assert var_14.skip_gitignore is False
    assert var_14.line_length == 79
    assert var_14.wrap_length == 0
    assert var_14.line_ending == ''
    assert var_14.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_14.no_sections is False
    assert f'{type(var_14.known_future_library).__module__}.{type(var_14.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.known_future_library) == 1
    assert f'{type(var_14.known_third_party).__module__}.{type(var_14.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.known_third_party) == 0
    assert f'{type(var_14.known_first_party).__module__}.{type(var_14.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.known_first_party) == 0
    assert f'{type(var_14.known_local_folder).__module__}.{type(var_14.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.known_local_folder) == 0
    assert f'{type(var_14.known_standard_library).__module__}.{type(var_14.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.known_standard_library) == 234
    assert f'{type(var_14.extra_standard_library).__module__}.{type(var_14.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.extra_standard_library) == 0
    assert var_14.known_other == {}
    assert var_14.multi_line_output == module_2.WrapModes.GRID
    assert var_14.forced_separate == ()
    assert var_14.indent == '    '
    assert var_14.comment_prefix == '  #'
    assert var_14.length_sort is False
    assert var_14.length_sort_straight is False
    assert f'{type(var_14.length_sort_sections).__module__}.{type(var_14.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.length_sort_sections) == 0
    assert f'{type(var_14.add_imports).__module__}.{type(var_14.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.add_imports) == 0
    assert f'{type(var_14.remove_imports).__module__}.{type(var_14.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.remove_imports) == 0
    assert var_14.append_only is False
    assert var_14.reverse_relative is False
    assert var_14.force_single_line is False
    assert var_14.single_line_exclusions == ()
    assert var_14.default_section == 'THIRDPARTY'
    assert var_14.import_headings == {}
    assert var_14.import_footers == {}
    assert var_14.balanced_wrapping is False
    assert var_14.use_parentheses is False
    assert var_14.order_by_type is True
    assert var_14.atomic is False
    assert var_14.lines_before_imports == -1
    assert var_14.lines_after_imports == -1
    assert var_14.lines_between_sections == 1
    assert var_14.lines_between_types == 0
    assert var_14.combine_as_imports is False
    assert var_14.combine_star is False
    assert var_14.include_trailing_comma is False
    assert var_14.from_first is False
    assert var_14.verbose is False
    assert var_14.quiet is False
    assert var_14.force_adds is False
    assert var_14.force_alphabetical_sort_within_sections is False
    assert var_14.force_alphabetical_sort is False
    assert var_14.force_grid_wrap == 0
    assert var_14.force_sort_within_sections is False
    assert var_14.lexicographical is False
    assert var_14.group_by_package is False
    assert var_14.ignore_whitespace is False
    assert f'{type(var_14.no_lines_before).__module__}.{type(var_14.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.no_lines_before) == 0
    assert var_14.no_inline_sort is False
    assert var_14.ignore_comments is False
    assert var_14.case_sensitive is False
    assert f'{type(var_14.sources).__module__}.{type(var_14.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_14.sources) == 1
    assert var_14.virtual_env == ''
    assert var_14.conda_env == ''
    assert var_14.ensure_newline_before_comments is False
    assert var_14.directory == '/workspace'
    assert var_14.profile == ''
    assert var_14.honor_noqa is False
    assert f'{type(var_14.src_paths).__module__}.{type(var_14.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_14.src_paths) == 2
    assert var_14.remove_redundant_aliases is False
    assert var_14.float_to_top is False
    assert var_14.filter_files is False
    assert var_14.formatter == ''
    assert var_14.formatting_function is None
    assert var_14.color_output is False
    assert f'{type(var_14.treat_comments_as_code).__module__}.{type(var_14.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.treat_comments_as_code) == 0
    assert var_14.treat_all_comments_as_code is False
    assert f'{type(var_14.supported_extensions).__module__}.{type(var_14.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.supported_extensions) == 4
    assert f'{type(var_14.blocked_extensions).__module__}.{type(var_14.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.blocked_extensions) == 1
    assert f'{type(var_14.constants).__module__}.{type(var_14.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.constants) == 0
    assert f'{type(var_14.classes).__module__}.{type(var_14.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.classes) == 0
    assert f'{type(var_14.variables).__module__}.{type(var_14.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.variables) == 0
    assert var_14.dedup_headings is False
    assert var_14.only_sections is False
    assert var_14.only_modified is False
    assert var_14.combine_straight_imports is False
    assert var_14.auto_identify_namespace_packages is True
    assert f'{type(var_14.namespace_packages).__module__}.{type(var_14.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_14.namespace_packages) == 0
    assert var_14.follow_links is True
    assert var_14.indented_import_headings is True
    assert var_14.honor_case_in_force_sorted_sections is False
    assert var_14.sort_relative_in_force_sorted_sections is False
    assert var_14.overwrite_in_place is False
    assert var_14.reverse_sort is False
    assert var_14.star_first is False
    assert var_14.git_ls_files == {}
    assert var_14.format_error == '{error}: {message}'
    assert var_14.format_success == '{success}: {message}'
    assert var_14.sort_order == 'natural'
    assert var_14.sort_reexports is False
    assert var_14.split_on_trailing_comma is False
    var_15 = []
    var_16 = []
    var_17 = list(var_2)
    var_18 = len(var_17)
    var_19 = len(var_15)
    var_20 = "print('another')"
    var_21 = module_1.Config()
    assert f'{type(var_21).__module__}.{type(var_21).__qualname__}' == 'isort.settings.Config'
    assert var_21.py_version == 'py3'
    assert f'{type(var_21.force_to_top).__module__}.{type(var_21.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.force_to_top) == 0
    assert f'{type(var_21.skip).__module__}.{type(var_21.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.skip) == 19
    assert f'{type(var_21.extend_skip).__module__}.{type(var_21.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.extend_skip) == 0
    assert f'{type(var_21.skip_glob).__module__}.{type(var_21.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.skip_glob) == 0
    assert f'{type(var_21.extend_skip_glob).__module__}.{type(var_21.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.extend_skip_glob) == 0
    assert var_21.skip_gitignore is False
    assert var_21.line_length == 79
    assert var_21.wrap_length == 0
    assert var_21.line_ending == ''
    assert var_21.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_21.no_sections is False
    assert f'{type(var_21.known_future_library).__module__}.{type(var_21.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.known_future_library) == 1
    assert f'{type(var_21.known_third_party).__module__}.{type(var_21.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.known_third_party) == 0
    assert f'{type(var_21.known_first_party).__module__}.{type(var_21.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.known_first_party) == 0
    assert f'{type(var_21.known_local_folder).__module__}.{type(var_21.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.known_local_folder) == 0
    assert f'{type(var_21.known_standard_library).__module__}.{type(var_21.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.known_standard_library) == 234
    assert f'{type(var_21.extra_standard_library).__module__}.{type(var_21.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.extra_standard_library) == 0
    assert var_21.known_other == {}
    assert var_21.multi_line_output == module_2.WrapModes.GRID
    assert var_21.forced_separate == ()
    assert var_21.indent == '    '
    assert var_21.comment_prefix == '  #'
    assert var_21.length_sort is False
    assert var_21.length_sort_straight is False
    assert f'{type(var_21.length_sort_sections).__module__}.{type(var_21.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.length_sort_sections) == 0
    assert f'{type(var_21.add_imports).__module__}.{type(var_21.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.add_imports) == 0
    assert f'{type(var_21.remove_imports).__module__}.{type(var_21.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.remove_imports) == 0
    assert var_21.append_only is False
    assert var_21.reverse_relative is False
    assert var_21.force_single_line is False
    assert var_21.single_line_exclusions == ()
    assert var_21.default_section == 'THIRDPARTY'
    assert var_21.import_headings == {}
    assert var_21.import_footers == {}
    assert var_21.balanced_wrapping is False
    assert var_21.use_parentheses is False
    assert var_21.order_by_type is True
    assert var_21.atomic is False
    assert var_21.lines_before_imports == -1
    assert var_21.lines_after_imports == -1
    assert var_21.lines_between_sections == 1
    assert var_21.lines_between_types == 0
    assert var_21.combine_as_imports is False
    assert var_21.combine_star is False
    assert var_21.include_trailing_comma is False
    assert var_21.from_first is False
    assert var_21.verbose is False
    assert var_21.quiet is False
    assert var_21.force_adds is False
    assert var_21.force_alphabetical_sort_within_sections is False
    assert var_21.force_alphabetical_sort is False
    assert var_21.force_grid_wrap == 0
    assert var_21.force_sort_within_sections is False
    assert var_21.lexicographical is False
    assert var_21.group_by_package is False
    assert var_21.ignore_whitespace is False
    assert f'{type(var_21.no_lines_before).__module__}.{type(var_21.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.no_lines_before) == 0
    assert var_21.no_inline_sort is False
    assert var_21.ignore_comments is False
    assert var_21.case_sensitive is False
    assert f'{type(var_21.sources).__module__}.{type(var_21.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_21.sources) == 1
    assert var_21.virtual_env == ''
    assert var_21.conda_env == ''
    assert var_21.ensure_newline_before_comments is False
    assert var_21.directory == '/workspace'
    assert var_21.profile == ''
    assert var_21.honor_noqa is False
    assert f'{type(var_21.src_paths).__module__}.{type(var_21.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_21.src_paths) == 2
    assert var_21.remove_redundant_aliases is False
    assert var_21.float_to_top is False
    assert var_21.filter_files is False
    assert var_21.formatter == ''
    assert var_21.formatting_function is None
    assert var_21.color_output is False
    assert f'{type(var_21.treat_comments_as_code).__module__}.{type(var_21.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.treat_comments_as_code) == 0
    assert var_21.treat_all_comments_as_code is False
    assert f'{type(var_21.supported_extensions).__module__}.{type(var_21.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.supported_extensions) == 4
    assert f'{type(var_21.blocked_extensions).__module__}.{type(var_21.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.blocked_extensions) == 1
    assert f'{type(var_21.constants).__module__}.{type(var_21.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.constants) == 0
    assert f'{type(var_21.classes).__module__}.{type(var_21.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.classes) == 0
    assert f'{type(var_21.variables).__module__}.{type(var_21.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.variables) == 0
    assert var_21.dedup_headings is False
    assert var_21.only_sections is False
    assert var_21.only_modified is False
    assert var_21.combine_straight_imports is False
    assert var_21.auto_identify_namespace_packages is True
    assert f'{type(var_21.namespace_packages).__module__}.{type(var_21.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_21.namespace_packages) == 0
    assert var_21.follow_links is True
    assert var_21.indented_import_headings is True
    assert var_21.honor_case_in_force_sorted_sections is False
    assert var_21.sort_relative_in_force_sorted_sections is False
    assert var_21.overwrite_in_place is False
    assert var_21.reverse_sort is False
    assert var_21.star_first is False
    assert var_21.git_ls_files == {}
    assert var_21.format_error == '{error}: {message}'
    assert var_21.format_success == '{success}: {message}'
    assert var_21.sort_order == 'natural'
    assert var_21.sort_reexports is False
    assert var_21.split_on_trailing_comma is False
    var_22 = []
    var_23 = [var_18, var_19]
    var_24 = module_0.find(var_23, var_21, var_1, var_22)
    var_25 = list(var_24)
    var_26 = len(var_25)
    var_27 = True
    var_28 = module_1.Config()
    assert f'{type(var_28).__module__}.{type(var_28).__qualname__}' == 'isort.settings.Config'
    assert var_28.py_version == 'py3'
    assert f'{type(var_28.force_to_top).__module__}.{type(var_28.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.force_to_top) == 0
    assert f'{type(var_28.skip).__module__}.{type(var_28.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.skip) == 19
    assert f'{type(var_28.extend_skip).__module__}.{type(var_28.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.extend_skip) == 0
    assert f'{type(var_28.skip_glob).__module__}.{type(var_28.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.skip_glob) == 0
    assert f'{type(var_28.extend_skip_glob).__module__}.{type(var_28.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.extend_skip_glob) == 0
    assert var_28.skip_gitignore is False
    assert var_28.line_length == 79
    assert var_28.wrap_length == 0
    assert var_28.line_ending == ''
    assert var_28.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_28.no_sections is False
    assert f'{type(var_28.known_future_library).__module__}.{type(var_28.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.known_future_library) == 1
    assert f'{type(var_28.known_third_party).__module__}.{type(var_28.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.known_third_party) == 0
    assert f'{type(var_28.known_first_party).__module__}.{type(var_28.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.known_first_party) == 0
    assert f'{type(var_28.known_local_folder).__module__}.{type(var_28.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.known_local_folder) == 0
    assert f'{type(var_28.known_standard_library).__module__}.{type(var_28.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.known_standard_library) == 234
    assert f'{type(var_28.extra_standard_library).__module__}.{type(var_28.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.extra_standard_library) == 0
    assert var_28.known_other == {}
    assert var_28.multi_line_output == module_2.WrapModes.GRID
    assert var_28.forced_separate == ()
    assert var_28.indent == '    '
    assert var_28.comment_prefix == '  #'
    assert var_28.length_sort is False
    assert var_28.length_sort_straight is False
    assert f'{type(var_28.length_sort_sections).__module__}.{type(var_28.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.length_sort_sections) == 0
    assert f'{type(var_28.add_imports).__module__}.{type(var_28.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.add_imports) == 0
    assert f'{type(var_28.remove_imports).__module__}.{type(var_28.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.remove_imports) == 0
    assert var_28.append_only is False
    assert var_28.reverse_relative is False
    assert var_28.force_single_line is False
    assert var_28.single_line_exclusions == ()
    assert var_28.default_section == 'THIRDPARTY'
    assert var_28.import_headings == {}
    assert var_28.import_footers == {}
    assert var_28.balanced_wrapping is False
    assert var_28.use_parentheses is False
    assert var_28.order_by_type is True
    assert var_28.atomic is False
    assert var_28.lines_before_imports == -1
    assert var_28.lines_after_imports == -1
    assert var_28.lines_between_sections == 1
    assert var_28.lines_between_types == 0
    assert var_28.combine_as_imports is False
    assert var_28.combine_star is False
    assert var_28.include_trailing_comma is False
    assert var_28.from_first is False
    assert var_28.verbose is False
    assert var_28.quiet is False
    assert var_28.force_adds is False
    assert var_28.force_alphabetical_sort_within_sections is False
    assert var_28.force_alphabetical_sort is False
    assert var_28.force_grid_wrap == 0
    assert var_28.force_sort_within_sections is False
    assert var_28.lexicographical is False
    assert var_28.group_by_package is False
    assert var_28.ignore_whitespace is False
    assert f'{type(var_28.no_lines_before).__module__}.{type(var_28.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.no_lines_before) == 0
    assert var_28.no_inline_sort is False
    assert var_28.ignore_comments is False
    assert var_28.case_sensitive is False
    assert f'{type(var_28.sources).__module__}.{type(var_28.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_28.sources) == 1
    assert var_28.virtual_env == ''
    assert var_28.conda_env == ''
    assert var_28.ensure_newline_before_comments is False
    assert var_28.directory == '/workspace'
    assert var_28.profile == ''
    assert var_28.honor_noqa is False
    assert f'{type(var_28.src_paths).__module__}.{type(var_28.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_28.src_paths) == 2
    assert var_28.remove_redundant_aliases is False
    assert var_28.float_to_top is False
    assert var_28.filter_files is False
    assert var_28.formatter == ''
    assert var_28.formatting_function is None
    assert var_28.color_output is False
    assert f'{type(var_28.treat_comments_as_code).__module__}.{type(var_28.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.treat_comments_as_code) == 0
    assert var_28.treat_all_comments_as_code is False
    assert f'{type(var_28.supported_extensions).__module__}.{type(var_28.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.supported_extensions) == 4
    assert f'{type(var_28.blocked_extensions).__module__}.{type(var_28.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.blocked_extensions) == 1
    assert f'{type(var_28.constants).__module__}.{type(var_28.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.constants) == 0
    assert f'{type(var_28.classes).__module__}.{type(var_28.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.classes) == 0
    assert f'{type(var_28.variables).__module__}.{type(var_28.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.variables) == 0
    assert var_28.dedup_headings is False
    assert var_28.only_sections is False
    assert var_28.only_modified is False
    assert var_28.combine_straight_imports is False
    assert var_28.auto_identify_namespace_packages is True
    assert f'{type(var_28.namespace_packages).__module__}.{type(var_28.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_28.namespace_packages) == 0
    assert var_28.follow_links is True
    assert var_28.indented_import_headings is True
    assert var_28.honor_case_in_force_sorted_sections is False
    assert var_28.sort_relative_in_force_sorted_sections is False
    assert var_28.overwrite_in_place is False
    assert var_28.reverse_sort is False
    assert var_28.star_first is False
    assert var_28.git_ls_files == {}
    assert var_28.format_error == '{error}: {message}'
    assert var_28.format_success == '{success}: {message}'
    assert var_28.sort_order == 'natural'
    assert var_28.sort_reexports is False
    assert var_28.split_on_trailing_comma is False
    var_29 = []
    var_30 = []
    var_31 = module_0.find(var_13, var_28, var_29, var_30)
    var_32 = list(var_31)
    var_33 = len(var_32)
    var_34 = module_1.Config()
    assert f'{type(var_34).__module__}.{type(var_34).__qualname__}' == 'isort.settings.Config'
    assert var_34.py_version == 'py3'
    assert f'{type(var_34.force_to_top).__module__}.{type(var_34.force_to_top).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.force_to_top) == 0
    assert f'{type(var_34.skip).__module__}.{type(var_34.skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.skip) == 19
    assert f'{type(var_34.extend_skip).__module__}.{type(var_34.extend_skip).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.extend_skip) == 0
    assert f'{type(var_34.skip_glob).__module__}.{type(var_34.skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.skip_glob) == 0
    assert f'{type(var_34.extend_skip_glob).__module__}.{type(var_34.extend_skip_glob).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.extend_skip_glob) == 0
    assert var_34.skip_gitignore is False
    assert var_34.line_length == 79
    assert var_34.wrap_length == 0
    assert var_34.line_ending == ''
    assert var_34.sections == ('FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER')
    assert var_34.no_sections is False
    assert f'{type(var_34.known_future_library).__module__}.{type(var_34.known_future_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.known_future_library) == 1
    assert f'{type(var_34.known_third_party).__module__}.{type(var_34.known_third_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.known_third_party) == 0
    assert f'{type(var_34.known_first_party).__module__}.{type(var_34.known_first_party).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.known_first_party) == 0
    assert f'{type(var_34.known_local_folder).__module__}.{type(var_34.known_local_folder).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.known_local_folder) == 0
    assert f'{type(var_34.known_standard_library).__module__}.{type(var_34.known_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.known_standard_library) == 234
    assert f'{type(var_34.extra_standard_library).__module__}.{type(var_34.extra_standard_library).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.extra_standard_library) == 0
    assert var_34.known_other == {}
    assert var_34.multi_line_output == module_2.WrapModes.GRID
    assert var_34.forced_separate == ()
    assert var_34.indent == '    '
    assert var_34.comment_prefix == '  #'
    assert var_34.length_sort is False
    assert var_34.length_sort_straight is False
    assert f'{type(var_34.length_sort_sections).__module__}.{type(var_34.length_sort_sections).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.length_sort_sections) == 0
    assert f'{type(var_34.add_imports).__module__}.{type(var_34.add_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.add_imports) == 0
    assert f'{type(var_34.remove_imports).__module__}.{type(var_34.remove_imports).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.remove_imports) == 0
    assert var_34.append_only is False
    assert var_34.reverse_relative is False
    assert var_34.force_single_line is False
    assert var_34.single_line_exclusions == ()
    assert var_34.default_section == 'THIRDPARTY'
    assert var_34.import_headings == {}
    assert var_34.import_footers == {}
    assert var_34.balanced_wrapping is False
    assert var_34.use_parentheses is False
    assert var_34.order_by_type is True
    assert var_34.atomic is False
    assert var_34.lines_before_imports == -1
    assert var_34.lines_after_imports == -1
    assert var_34.lines_between_sections == 1
    assert var_34.lines_between_types == 0
    assert var_34.combine_as_imports is False
    assert var_34.combine_star is False
    assert var_34.include_trailing_comma is False
    assert var_34.from_first is False
    assert var_34.verbose is False
    assert var_34.quiet is False
    assert var_34.force_adds is False
    assert var_34.force_alphabetical_sort_within_sections is False
    assert var_34.force_alphabetical_sort is False
    assert var_34.force_grid_wrap == 0
    assert var_34.force_sort_within_sections is False
    assert var_34.lexicographical is False
    assert var_34.group_by_package is False
    assert var_34.ignore_whitespace is False
    assert f'{type(var_34.no_lines_before).__module__}.{type(var_34.no_lines_before).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.no_lines_before) == 0
    assert var_34.no_inline_sort is False
    assert var_34.ignore_comments is False
    assert var_34.case_sensitive is False
    assert f'{type(var_34.sources).__module__}.{type(var_34.sources).__qualname__}' == 'builtins.tuple'
    assert len(var_34.sources) == 1
    assert var_34.virtual_env == ''
    assert var_34.conda_env == ''
    assert var_34.ensure_newline_before_comments is False
    assert var_34.directory == '/workspace'
    assert var_34.profile == ''
    assert var_34.honor_noqa is False
    assert f'{type(var_34.src_paths).__module__}.{type(var_34.src_paths).__qualname__}' == 'builtins.tuple'
    assert len(var_34.src_paths) == 2
    assert var_34.remove_redundant_aliases is False
    assert var_34.float_to_top is False
    assert var_34.filter_files is False
    assert var_34.formatter == ''
    assert var_34.formatting_function is None
    assert var_34.color_output is False
    assert f'{type(var_34.treat_comments_as_code).__module__}.{type(var_34.treat_comments_as_code).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.treat_comments_as_code) == 0
    assert var_34.treat_all_comments_as_code is False
    assert f'{type(var_34.supported_extensions).__module__}.{type(var_34.supported_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.supported_extensions) == 4
    assert f'{type(var_34.blocked_extensions).__module__}.{type(var_34.blocked_extensions).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.blocked_extensions) == 1
    assert f'{type(var_34.constants).__module__}.{type(var_34.constants).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.constants) == 0
    assert f'{type(var_34.classes).__module__}.{type(var_34.classes).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.classes) == 0
    assert f'{type(var_34.variables).__module__}.{type(var_34.variables).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.variables) == 0
    assert var_34.dedup_headings is False
    assert var_34.only_sections is False
    assert var_34.only_modified is False
    assert var_34.combine_straight_imports is False
    assert var_34.auto_identify_namespace_packages is True
    assert f'{type(var_34.namespace_packages).__module__}.{type(var_34.namespace_packages).__qualname__}' == 'builtins.frozenset'
    assert len(var_34.namespace_packages) == 0
    assert var_34.follow_links is True
    assert var_34.indented_import_headings is True
    assert var_34.honor_case_in_force_sorted_sections is False
    assert var_34.sort_relative_in_force_sorted_sections is False
    assert var_34.overwrite_in_place is False
    assert var_34.reverse_sort is False
    assert var_34.star_first is False
    assert var_34.git_ls_files == {}
    assert var_34.format_error == '{error}: {message}'
    assert var_34.format_success == '{success}: {message}'
    assert var_34.sort_order == 'natural'
    assert var_34.sort_reexports is False
    assert var_34.split_on_trailing_comma is False
    var_35 = []
    var_36 = []
    var_37 = module_0.find(var_20, var_34, var_35, var_36)
    var_38 = list(var_37)
    var_39 = len(var_38)
    var_40 = len(var_35)